version: "2"
services:
  nginx-ssi:
    image: nginx
    ports:
      - "8100:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/location.d:/etc/nginx/location.d:ro
      - ./app:/usr/share/nginx/html:ro
    command: [nginx-debug, '-g', 'daemon off;']
  header:
    image: "node:alpine"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ../header:/home/node/app
    expose:
      - "8002"
    command: "npm start"
  product:
    image: "node:alpine"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ../product:/home/node/app
    expose:
      - "8003"
    command: "npm run old-start"
  advertising:
    image: "node:alpine"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ../advertising:/home/node/app
    expose:
      - "8004"
    command: "npm start"
